version: '3.9'

services:

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=tasklist
      - POSTGRES_USER=tasklist
      - POSTGRES_DB=tasklistdb
    privileged: true

  tasklist:
    depends_on:
      - postgres
    image: localhost/tasklist
    ports:
          - "8081:8080"